import { SquadPlayer, PlayerPosition } from '@/types/lineup';

export const SQUAD_PLAYERS: SquadPlayer[] = [
  // Goalkeeper
  {
    name: 'Ederson',
    imageUrl: require('@/assets/players/ederson.jpg'),
    rating: 8.4,
    position: PlayerPosition.GOALKEEPER,
    age: 30,
    shirtNumber: 31,
    displayPosition: 'GK',
    club: 'Manchester City',
  },
  // Defenders
  {
    name: 'Gvardiol',
    imageUrl: require('@/assets/players/gvardiol.jpg'),
    rating: 7.8,
    position: PlayerPosition.DEFENDER,
    age: 22,
    shirtNumber: 24,
    displayPosition: 'CB',
    club: 'Manchester City',
  },
  {
    name: 'Dias',
    imageUrl: require('@/assets/players/dias.jpg'),
    rating: 8.1,
    position: PlayerPosition.DEFENDER,
    age: 26,
    shirtNumber: 3,
    displayPosition: 'CB',
    club: 'Manchester City',
  },
  {
    name: 'Akanji',
    imageUrl: require('@/assets/players/akanji.jpg'),
    rating: 7.5,
    position: PlayerPosition.DEFENDER,
    age: 28,
    shirtNumber: 25,
    displayPosition: 'CB',
    club: 'Manchester City',
  },
  {
    name: 'Walker',
    imageUrl: require('@/assets/players/walker.jpg'),
    rating: 7.6,
    position: PlayerPosition.DEFENDER,
    age: 33,
    shirtNumber: 2,
    displayPosition: 'RB',
    club: 'Manchester City',
  },
  // Midfielders
  {
    name: 'Kovačić',
    imageUrl: require('@/assets/players/kovacic.jpg'),
    rating: 7.9,
    position: PlayerPosition.MIDFIELDER,
    age: 29,
    shirtNumber: 8,
    displayPosition: 'CM',
    club: 'Manchester City',
  },
  {
    name: 'Rodri',
    imageUrl: require('@/assets/players/rodri.jpg'),
    rating: 9.1,
    position: PlayerPosition.MIDFIELDER,
    isStarPlayer: true,
    age: 27,
    shirtNumber: 16,
    displayPosition: 'CDM',
    club: 'Manchester City',
  },
  {
    name: 'Bernardo',
    imageUrl: require('@/assets/players/bernardo.jpg'),
    rating: 8.3,
    position: PlayerPosition.MIDFIELDER,
    age: 29,
    shirtNumber: 20,
    displayPosition: 'CM',
    club: 'Manchester City',
  },
  // Forwards
  {
    name: 'Doku',
    imageUrl: require('@/assets/players/doku.jpg'),
    rating: 7.7,
    position: PlayerPosition.FORWARD,
    age: 22,
    shirtNumber: 11,
    displayPosition: 'LW',
    club: 'Manchester City',
  },
  {
    name: 'Haaland',
    imageUrl: require('@/assets/players/haaland.jpg'),
    rating: 9.4,
    position: PlayerPosition.FORWARD,
    isStarPlayer: true,
    age: 24,
    shirtNumber: 9,
    displayPosition: 'ST',
    club: 'Manchester City',
  },
  {
    name: 'Foden',
    imageUrl: require('@/assets/players/foden.jpg'),
    rating: 8.8,
    position: PlayerPosition.FORWARD,
    age: 24,
    shirtNumber: 47,
    displayPosition: 'RW',
    club: 'Manchester City',
  },
];

export const SUGGESTED_PLAYERS: SquadPlayer[] = [
  {
    name: 'Salah',
    imageUrl: require('@/assets/players/haaland.jpg'), // Placeholder
    rating: 8.9,
    position: PlayerPosition.FORWARD,
    age: 32,
    shirtNumber: 11,
    displayPosition: 'RW',
    club: 'Liverpool FC',
    isSuggested: true,
  },
  {
    name: 'Van Dijk',
    imageUrl: require('@/assets/players/dias.jpg'), // Placeholder
    rating: 8.7,
    position: PlayerPosition.DEFENDER,
    age: 32,
    shirtNumber: 4,
    displayPosition: 'CB',
    club: 'Liverpool FC',
    isSuggested: true,
  },
  {
    name: 'Alexander-Arnold',
    imageUrl: require('@/assets/players/walker.jpg'), // Placeholder
    rating: 8.5,
    position: PlayerPosition.DEFENDER,
    age: 25,
    shirtNumber: 66,
    displayPosition: 'RB',
    club: 'Liverpool FC',
    isSuggested: true,
  },
];
