import { TransferPlayer, RecentTransfer } from '@/types/transfer';
import { PlayerPosition } from '@/types/lineup';

export const SUGGESTED_TRANSFER_PLAYERS: TransferPlayer[] = [
  // Liverpool Players
  {
    name: 'Alisson B.',
    imageUrl: require('@/assets/players/ederson.jpg'),
    rating: 8.8,
    position: PlayerPosition.GOALKEEPER,
    displayPosition: 'GK',
    age: 31,
    shirtNumber: 1,
    club: 'Liverpool',
    isSuggested: true,
  },
  {
    name: 'Virgil V.',
    imageUrl: require('@/assets/players/dias.jpg'),
    rating: 8.9,
    position: PlayerPosition.DEFENDER,
    displayPosition: 'CB',
    age: 32,
    shirtNumber: 4,
    club: 'Liverpool',
    isSuggested: true,
  },
  {
    name: 'Trent A.',
    imageUrl: require('@/assets/players/walker.jpg'),
    rating: 8.3,
    position: PlayerPosition.DEFENDER,
    displayPosition: 'RB',
    age: 25,
    shirtNumber: 66,
    club: 'Liverpool',
    isSuggested: true,
  },
  {
    name: 'Mohamed S.',
    imageUrl: require('@/assets/players/doku.jpg'),
    rating: 9.0,
    position: PlayerPosition.FORWARD,
    displayPosition: 'RW',
    age: 31,
    shirtNumber: 11,
    club: 'Liverpool',
    isSuggested: true,
  },
  // Arsenal Players
  {
    name: 'William S.',
    imageUrl: require('@/assets/players/dias.jpg'),
    rating: 8.7,
    position: PlayerPosition.DEFENDER,
    displayPosition: 'CB',
    age: 26,
    shirtNumber: 6,
    club: 'Arsenal',
    isSuggested: true,
  },
  {
    name: 'Martin Ø.',
    imageUrl: require('@/assets/players/bernardo.jpg'),
    rating: 8.9,
    position: PlayerPosition.MIDFIELDER,
    displayPosition: 'CAM',
    age: 24,
    shirtNumber: 8,
    club: 'Arsenal',
    isSuggested: true,
  },
  {
    name: 'Declan R.',
    imageUrl: require('@/assets/players/rodri.jpg'),
    rating: 8.6,
    position: PlayerPosition.MIDFIELDER,
    displayPosition: 'CDM',
    age: 24,
    shirtNumber: 41,
    club: 'Arsenal',
    isSuggested: true,
  },
  {
    name: 'Bukayo S.',
    imageUrl: require('@/assets/players/doku.jpg'),
    rating: 8.8,
    position: PlayerPosition.FORWARD,
    displayPosition: 'RW',
    age: 22,
    shirtNumber: 7,
    club: 'Arsenal',
    isSuggested: true,
  },
  // Chelsea Players
  {
    name: 'Reece J.',
    imageUrl: require('@/assets/players/walker.jpg'),
    rating: 8.3,
    position: PlayerPosition.DEFENDER,
    displayPosition: 'RB',
    age: 23,
    shirtNumber: 24,
    club: 'Chelsea',
    isSuggested: true,
  },
  {
    name: 'Enzo F.',
    imageUrl: require('@/assets/players/kovacic.jpg'),
    rating: 8.4,
    position: PlayerPosition.MIDFIELDER,
    displayPosition: 'CM',
    age: 23,
    shirtNumber: 5,
    club: 'Chelsea',
    isSuggested: true,
  },
  {
    name: 'Cole P.',
    imageUrl: require('@/assets/players/foden.jpg'),
    rating: 8.6,
    position: PlayerPosition.FORWARD,
    displayPosition: 'LW',
    age: 21,
    shirtNumber: 20,
    club: 'Chelsea',
    isSuggested: true,
  },
  // Real Madrid Players
  {
    name: 'Jude B.',
    imageUrl: require('@/assets/players/foden.jpg'),
    rating: 9.3,
    position: PlayerPosition.MIDFIELDER,
    displayPosition: 'CAM',
    age: 20,
    shirtNumber: 5,
    club: 'Real Madrid',
    isSuggested: true,
  },
  {
    name: 'Vinicius Jr.',
    imageUrl: require('@/assets/players/doku.jpg'),
    rating: 9.4,
    position: PlayerPosition.FORWARD,
    displayPosition: 'LW',
    age: 23,
    shirtNumber: 7,
    club: 'Real Madrid',
    isSuggested: true,
  },
  // Bayern Munich Players
  {
    name: 'Jamal M.',
    imageUrl: require('@/assets/players/foden.jpg'),
    rating: 9.1,
    position: PlayerPosition.MIDFIELDER,
    displayPosition: 'CAM',
    age: 20,
    shirtNumber: 42,
    club: 'Bayern Munich',
    isSuggested: true,
  },
  {
    name: 'Harry K.',
    imageUrl: require('@/assets/players/haaland.jpg'),
    rating: 9.0,
    position: PlayerPosition.FORWARD,
    displayPosition: 'ST',
    age: 30,
    shirtNumber: 9,
    club: 'Bayern Munich',
    isSuggested: true,
  },
  // PSG Players
  {
    name: 'Kylian M.',
    imageUrl: require('@/assets/players/doku.jpg'),
    rating: 9.6,
    position: PlayerPosition.FORWARD,
    displayPosition: 'ST',
    age: 25,
    shirtNumber: 7,
    club: 'PSG',
    isSuggested: true,
  },
];

export const RECENT_TRANSFERS: RecentTransfer[] = [
  {
    playerName: 'Jude Bellingham',
    fromClub: 'Borussia Dortmund',
    toClub: 'Real Madrid',
    fee: '103M€',
    date: 'Jun 2025',
    position: 'CAM',
  },
  {
    playerName: 'Declan Rice',
    fromClub: 'West Ham',
    toClub: 'Arsenal',
    fee: '117M€',
    date: 'Jul 2025',
    position: 'CDM',
  },
  {
    playerName: 'Rasmus Højlund',
    fromClub: 'Atalanta',
    toClub: 'Manchester United',
    fee: '75M€',
    date: 'Aug 2025',
    position: 'ST',
  },
  {
    playerName: 'Moisés Caicedo',
    fromClub: 'Brighton',
    toClub: 'Chelsea',
    fee: '116M€',
    date: 'Aug 2025',
    position: 'CDM',
  },
  {
    playerName: 'Dominik Szoboszlai',
    fromClub: 'RB Leipzig',
    toClub: 'Liverpool',
    fee: '70M€',
    date: 'Jul 2025',
    position: 'CAM',
  },
  {
    playerName: 'Matheus Nunes',
    fromClub: 'Wolves',
    toClub: 'Manchester City',
    fee: '53M€',
    date: 'Sep 2025',
    position: 'CM',
  },
  {
    playerName: 'James Maddison',
    fromClub: 'Leicester City',
    toClub: 'Tottenham',
    fee: '45M€',
    date: 'Jun 2025',
    position: 'CAM',
  },
  {
    playerName: 'Alexis Mac Allister',
    fromClub: 'Brighton',
    toClub: 'Liverpool',
    fee: '38M€',
    date: 'Jun 2025',
    position: 'CM',
  },
];

export const getAvailableClubs = (players: TransferPlayer[]): string[] => {
  const clubs = [...new Set(players.map((p) => p.club))].sort();
  return ['All', ...clubs];
};
